### ISSUE TITLE
Lexical crash when building release with `NAMESPACE=1`

### ISSUE THREAD

**Issue by wingyplus** [lexical-lsp/lexical#165]
I found it in the project https://github.com/wingyplus/dagger_ex. When I try to formatting after opening an editor I found an error:

```
01:09:33.924 [error] ** (ErlangError) Erlang error: {:erpc, :noconnection}
    (kernel 8.5.3) erpc.erl:710: :erpc.call/5
    (server 0.1.0) lib/lexical/server/provider/handlers/formatting.ex:13: LXRelease.Server.Provider.Handlers.Formatting.handle/2
    (server 0.1.0) lib/lexical/server/provider/queue.ex:100: anonymous fn/2 in LXRelease.Server.Provider.Queue.State.as_task/2
    (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

```

So, I open `.lexical/lexical.log` to see what's happens and found.

```
01:09:31.917 [error] Process #PID<0.2167.0> terminating
** (exit) exited in: GenServer.call(:"dagger_ex::node_process", {:start, ['/Users/thanabodee/src/github.com/lexical-lsp/lexical/_build/prod/rel/lexical/lib/common-0.1.0/ebin', '/Users/thanabodee/src/github.com/lexical-lsp/lexical/_build/prod/rel/lexical/lib/elixir_sense-2.0.0/ebin', '/Users/thanabodee/src/github.com/lexical-lsp/lexical/_build/prod/rel/lexical/lib/path_glob-0.2.0/ebin', '/Users/thanabodee/src/github.com/lexical-lsp/lexical/_build/prod/rel/lexical/lib/remote_control-0.1.0/ebin']}, 3500)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
            (elixir 1.14.3) lib/io.ex:670: IO.chardata_to_string({:error, :bad_name})
            (elixir 1.14.3) lib/path.ex:548: Path.join/2
            (remote_control 0.1.0) lib/lexical/remote_control/project_node.ex:30: LXRelease.RemoteControl.ProjectNode.State.start/3
            (remote_control 0.1.0) lib/lexical/remote_control/project_node.ex:152: LXRelease.RemoteControl.ProjectNode.handle_call/3
            (stdlib 4.2) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.2) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.3) lib/gen_server.ex:1038: GenServer.call/3
    (remote_control 0.1.0) lib/lexical/remote_control/project_node.ex:106: LXRelease.RemoteControl.ProjectNode.start/3
    (remote_control 0.1.0) lib/lexical/remote_control.ex:24: LXRelease.RemoteControl.start_link/2
    (server 0.1.0) lib/lexical/server/project/node.ex:96: LXRelease.Server.Project.Node.start_node/1
    (server 0.1.0) lib/lexical/server/project/progress/support.ex:17: LXRelease.Server.Project.Progress.Support.with_progress/3
    (server 0.1.0) lib/lexical/server/project/node.ex:53: LXRelease.Server.Project.Node.init/1
    (stdlib 4.2) gen_server.erl:851: :gen_server.init_it/2
    (stdlib 4.2) gen_server.erl:814: :gen_server.init_it/6

```

**Comment by wingyplus** [comment]
I guess :code.priv_dir(:remote_control) returns :bad_name but it expected to return a path to point to port_wrapper.sh?

**Comment by scohen** [comment]
did you build a release?

**Comment by scohen** [comment]
I'm confused as to how this can happen. What's your setup?

**Comment by scottming** [comment]
`NAMESPACE=1 mix release lexical` can replicate this error; I haven't used it for a while.

**Comment by wingyplus** [comment]
Yes, I use mix release lexical and then run mix release lexical —overwrite with NAMESPACE=true 

Both command use MIX_ENV=prod

**Comment by wingyplus** [comment]
I see. The `NAMESPACE=1` change app name into `lx_remote_control`:

```
$ cat _build/prod/rel/lexical/lib/remote_control-0.1.0/ebin/lx_remote_control.app
{application,lx_remote_control,
             [{applications,[kernel,stdlib,elixir,logger,lx_common,elixir_sense]},
              {description,"lx_remote_control"},
              {modules,['Elixir.LXRelease.RemoteControl',
                        'Elixir.LXRelease.RemoteControl.Api',
                        'Elixir.LXRelease.RemoteControl.Api.Messages',
                        'Elixir.LXRelease.RemoteControl.Application',
                        'Elixir.LXRelease.RemoteControl.Bootstrap',
                        'Elixir.LXRelease.RemoteControl.Build',
                        'Elixir.LXRelease.RemoteControl.Build.CaptureIO',
                        'Elixir.LXRelease.RemoteControl.Build.CaptureServer',
                        'Elixir.LXRelease.RemoteControl.Build.Error',
                        'Elixir.LXRelease.RemoteControl.Build.Progress',
                        'Elixir.LXRelease.RemoteControl.Build.State',
                        'Elixir.LXRelease.RemoteControl.CodeIntelligence.Definition',
                        'Elixir.LXRelease.RemoteControl.CodeMod.Ast',
                        'Elixir.LXRelease.RemoteControl.CodeMod.Diff',
                        'Elixir.LXRelease.RemoteControl.CodeMod.Format',
                        'Elixir.LXRelease.RemoteControl.CodeMod.ReplaceWithUnderscore',
                        'Elixir.LXRelease.RemoteControl.CompileTracer',
                        'Elixir.LXRelease.RemoteControl.Completion',
                        'Elixir.LXRelease.RemoteControl.Completion.Result',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Behaviour',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.BitstringOption',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Callback',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Exception',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Function',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Macro',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.MixTask',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Module',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.ModuleAttribute',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Protocol',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Snippet',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Struct',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.StructField',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Typespec',
                        'Elixir.LXRelease.RemoteControl.Completion.Result.Variable',
                        'Elixir.LXRelease.RemoteControl.Mix',
                        'Elixir.LXRelease.RemoteControl.ModuleMappings',
                        'Elixir.LXRelease.RemoteControl.ModuleMappings.State',
                        'Elixir.LXRelease.RemoteControl.ProjectNode',
                        'Elixir.LXRelease.RemoteControl.ProjectNode.State',
                        'Elixir.LXRelease.RemoteControl.ProjectNodeSupervisor',
                        'Elixir.Mix.Tasks.Deps.SafeCompile']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.LXRelease.RemoteControl.Application',[]}}]}.
```

**Comment by scohen** [comment]
Yeah, that makes sense. I thought the remapper looked for `:remote_control` atoms. What if you do 

```elixir
# project_node.ex
@remote_control_app :remote_control

# then later
:code.priv_dir(@remote_control_app)
```
?

**Comment by scottming** [comment]
@wingyplus 

```elixir
    @remote_control_app "remote_control"

    defp port_wrapper_executable do
      @remote_control_app
      |> String.to_existing_atom()
      |> :code.priv_dir()
      |> Path.join("port_wrapper.sh")
    end
   ```
   
   These code can temporary solve your problem
