### ISSUE TITLE
Closing one too many blocks causes an error.

### ISSUE THREAD

**Issue by HeapUnderfl0w** [lexical-lsp/lexical#272]
Closing one too many blocks causes lexical to error out.

MRE:

```elixir
defmodule A do
  def x() d # typo here
  end
end
```

results in the following crash:

```
LSP :: Error from the Language Server: ** (CaseClauseError) no case clause matching: {:error, {[line: 58, column: 2], {"unexpected reserved word: ", "\n\n    HINT: it looks like the \"end\" on line 53 does not have a matching \"do\" defined before it\n"}, "end"}}
    (lx_server 0.1.0) lib/lexical/server/provider/code_action/replace_with_underscore.ex:37: LXical.Server.Provider.CodeAction.ReplaceWithUnderscore.build_code_action/4
    (lx_server 0.1.0) lib/lexical/server/provider/code_action/replace_with_underscore.ex:22: anonymous fn/3 in LXical.Server.Provider.CodeAction.ReplaceWithUnderscore.apply/2
    (elixir 1.14.5) lib/enum.ex:4249: Enum.flat_map_list/2
    (lx_server 0.1.0) lib/lexical/server/provider/handlers/code_action.ex:13: LXical.Server.Provider.Handlers.CodeAction.handle/2
    (lx_server 0.1.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXical.Server.Provider.Queue.State.as_task/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
````

System: `Nixos x64 (Kernel 6.3.12)`
Erlang: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 13.2.2.2`
Elixir: `Elixir 1.14.5 (compiled with Erlang/OTP 25)`
Lexical Rev: 6afbc75aef6ea17c40fb41acde50a5d0fcd78bb3

**Comment by scohen** [comment]
@HeapUnderfl0w I think there's more to that error; I can't reproduce it, and it's complaining about a ",".

**Comment by HeapUnderfl0w** [comment]
right, yea sorry. this was a bit copied together as i didnt have the time for a full example.

To reliably reproduce this on my end i did this now:

create a new mix project (`mix new mre`)

replace the content of `mre/lib/mre.ex` with

```elixir
defmodule Mre do
  def test(a, true) do
  end
end
```

now delete the `o` from `do` so that the file now reads the following:

```elixir
defmodule Mre do
  def test(a, true) d
  end
end
```

this produces the following error (this time with correct line numbers):

```
LSP :: Error from the Language Server: ** (CaseClauseError) no case clause matching: {:error, {[line: 4, column: 1], {"unexpected reserved word: ", "\n\n    HINT: it looks like the \"end\" on line 3 does not have a matching \"do\" defined before it\n"}, "end"}}
    (lx_server 0.1.0) lib/lexical/server/provider/code_action/replace_with_underscore.ex:37: LXical.Server.Provider.CodeAction.ReplaceWithUnderscore.build_code_action/4
    (lx_server 0.1.0) lib/lexical/server/provider/code_action/replace_with_underscore.ex:22: anonymous fn/3 in LXical.Server.Provider.CodeAction.ReplaceWithUnderscore.apply/2
    (elixir 1.14.5) lib/enum.ex:4249: Enum.flat_map_list/2
    (lx_server 0.1.0) lib/lexical/server/provider/handlers/code_action.ex:13: LXical.Server.Provider.Handlers.CodeAction.handle/2
    (lx_server 0.1.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXical.Server.Provider.Queue.State.as_task/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
 (Internal Error)
```
 
 the actual error *is* correctly forwarded back to emacs tho
 
![image](https://github.com/lexical-lsp/lexical/assets/28512568/ea2b78c2-4ee2-4aa2-a6e0-df29bb0bff52)
