### ISSUE TITLE
Request textDocument/completion failed

### ISSUE THREAD

**Issue by objectuser** [lexical-lsp/lexical#295]
Compiled with Elixir 1.15.4, Erlang 26.0.2:

```sh
$ NAMESPACE=1 mix release lexical --overwrite
```

```elixir
[Error - 10:02:01 AM] Request textDocument/completion failed.
  Message: ** (FunctionClauseError) no function clause matching in LXical.Server.CodeIntelligence.Completion.complete/4
    (lx_server 0.1.0) lib/lexical/server/code_intelligence/completion.ex:30: LXical.Server.CodeIntelligence.Completion.complete(%LXical.Project{root_uri: "file:///...", mix_exs_uri: "file:///.../mix.exs", mix_project?: true, mix_env: nil, mix_target: nil, env_variables: %{}, project_module: nil}, #LXical.Document<path: "/.../...ex", version: 10, dirty?: false, lines: %Lines<"defmodule ... do..."(70 lines)>, ...>, #Protocol.Types.Position<[line: 51, character: 73]>, #Protocol.Types.Completion.Context<[trigger_kind: :invoked]>)
    (lx_server 0.1.0) lib/lexical/server/provider/handlers/completion.ex:12: LXical.Server.Provider.Handlers.Completion.handle/2
    (lx_server 0.1.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXical.Server.Provider.Queue.State.as_task/2
    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.4) lib/task/supervised.ex:36: Task.Supervised.reply/4

  Code: -32603 
```

Recompiled without `NAMESPACE=1` and the error does not occur.

Related Discord conversation [here](https://discord.com/channels/269508806759809042/918183981344772117/1134517086853546024).

**Comment by scohen** [comment]
Talked a lot about this on discord; 
This issue didn't recur after @objectuser killed extraneous BEAM processes on his laptop. Closing for now, as I was also experiencing this sporadically before the refactor of namespacing.
