### ISSUE TITLE
Crash when completing

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#303]
I got the following crash when completing the following:
```elixir
def enable| do 
end
```

```
09:52:56.434 [error] ** (ErlangError) Erlang error: {:exception, {:case_clause, :expr}, [{LXical.RemoteControl.Completion.Candidate.ArgumentNames, :extract_name, 2, [file: 'lib/lexical/remote_control/completion/candidate/argument_names.ex', line: 87]}, {LXical.RemoteControl.Completion.Candidate.ArgumentNames, :"-preprocess/1-fun-0-", 2, [file: 'lib/lexical/remote_control/completion/candidate/argument_names.ex', line: 74]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 2468]}, {LXical.RemoteControl.Completion.Candidate.ArgumentNames, :preprocess, 1, [file: 'lib/lexical/remote_control/completion/candidate/argument_names.ex', line: 70]}, {LXical.RemoteControl.Completion.Candidate.ArgumentNames, :from_elixir_sense, 2, [file: 'lib/lexical/remote_control/completion/candidate/argument_names.ex', line: 27]}, {LXical.RemoteControl.Completion.Candidate.Callback, :new, 1, [file: 'lib/lexical/remote_control/completion/candidate.ex', line: 28]}, {LXical.RemoteControl.Completion, :"-elixir_sense_expand/2-fun-0-", 2, [file: 'lib/lexical/remote_control/completion.ex', line: 19]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 2468]}]}
    (kernel 8.5.4) erpc.erl:702: :erpc.call/5
    (lx_server 0.1.0) lib/lexical/server/code_intelligence/completion.ex:75: LXical.Server.CodeIntelligence.Completion.completions/3
    (lx_server 0.1.0) lib/lexical/server/code_intelligence/completion.ex:38: LXical.Server.CodeIntelligence.Completion.complete/4
    (lx_server 0.1.0) lib/lexical/server/provider/handlers/completion.ex:12: LXical.Server.Provider.Handlers.Completion.handle/2
    (lx_server 0.1.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXical.Server.Provider.Queue.State.as_task/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by scottming** [comment]
Interesting, I never encountered this.
