### ISSUE TITLE
`invalid port name` error when using GH release

### ISSUE THREAD

**Issue by rktjmp** [lexical-lsp/lexical#451]
Elixir via asdf:

```
elixir          1.15.5-otp-26
erlang          26.0.2
```

Lexical version: 0.4.0 GH release (Building from source with the above versions does ***not*** exhibit the same issue).

```
epmd -names
epmd: up and running on port 4369 with data:
name local at port 42495
name manager-project-4905 at port 33639
name manager-project-12415 at port 46737
```

Log

```
14:20:24.462 [info] Child {LoggerFileBackend, :general_log} of Supervisor Logger.Backends.Supervisor started
Pid: #PID<0.119.0>
Start Call: Logger.Backends.Watcher.start_link({{LoggerFileBackend, :general_log}, {LoggerFileBackend, :general_log}})
Restart: :transient
Shutdown: 5000
Type: :worker
14:20:24.462 [info] Child Logger.Backends.Supervisor of Supervisor Logger.Backends.Internal started
Pid: #PID<0.118.0>
Start Call: Logger.Backends.Supervisor.start_link([{LoggerFileBackend, :general_log}])
Restart: :permanent
Shutdown: :infinity
Type: :supervisor
14:20:24.462 [info] Child Logger.Backends.Internal of Supervisor Logger.Supervisor started
Pid: #PID<0.114.0>
Start Call: Logger.Backends.Internal.start_link([])
Restart: :permanent
Shutdown: :infinity
Type: :supervisor
14:20:24.462 [info] Application logger started at :nonode@nohost
14:20:27.045 [info] Child :ttb_autostart of Supervisor :runtime_tools_sup started
Pid: #PID<0.125.0>
Start Call: :ttb_autostart.start_link()
Restart: :temporary
Shutdown: 3000
Type: :worker
14:20:27.045 [info] Application runtime_tools started at :nonode@nohost
14:20:27.047 [info] Application erts started at :nonode@nohost
14:20:27.047 [info] Application lx_lexical_shared started at :nonode@nohost
14:20:27.047 [info] Application lx_lexical_test started at :nonode@nohost
14:20:27.047 [info] Application lx_sourceror started at :nonode@nohost
14:20:27.047 [info] Application lx_common started at :nonode@nohost
14:20:27.047 [info] Application lx_elixir_sense started at :nonode@nohost
14:20:27.047 [info] Application jason started at :nonode@nohost
14:20:27.047 [info] Application logger_file_backend started at :nonode@nohost
14:20:27.047 [info] Application lx_path_glob started at :nonode@nohost
14:20:27.048 [info] Application lx_proto started at :nonode@nohost
14:20:27.048 [info] Application lx_protocol started at :nonode@nohost
14:20:27.071 [info] Child LXical.Document.Store of Supervisor LXical.Server.Supervisor started
<bunch of start_links>
14:20:27.087 [info] Application lx_server started at :nonode@nohost
14:20:27.107 [info] Starting project at uri file:///home/<user>/projects/client/<project>-web/<project>
14:20:27.132 [info] Child {LXical.Server.Project.Progress, "<project>"} of Supervisor :"<project>::supervisor" started
Pid: #PID<0.148.0>
Start Call: LXical.Server.Project.Progress.start_link(%{__struct__: LXical.Project, project_module: nil, project_config: [], entropy: 12415, mix_exs_uri: "file:///home/<user>/projects/client/<project>-web/<project>/mix.exs", mix_project?: true, root_uri: "file:///home/<user>/projects/client/<project>-web/<project>", env_variables: %{}, mix_env: nil, mix_target: nil})
```

Note the `nonode@nohost`, intentional?

```Restart: :permanent
Shutdown: 5000
Type: :worker
14:20:27.155 [info] Child :erl_epmd of Supervisor :net_sup started
Pid: #PID<0.152.0>
Start Call: :erl_epmd.start_link()
Restart: :permanent
Shutdown: 2000
Type: :worker
14:20:27.157 [info] Child :auth of Supervisor :net_sup started
Pid: #PID<0.153.0>
Start Call: :auth.start_link()
Restart: :permanent
Shutdown: 2000
Type: :worker
14:20:27.176 [info] Child :net_kernel of Supervisor :net_sup started
Pid: #PID<0.154.0>
Start Call: :net_kernel.start_link(%{name: :"manager-<project>-12415@127.0.0.1", supervisor: :net_sup_dynamic, net_tickintensity: 4, net_ticktime: 60, name_domain: :longnames, clean_halt: false})
```

`manger-xxx-ddd` is correct (exists in epmd at least).

```
Restart: :permanent
Shutdown: 2000
Type: :worker
14:20:27.176 [info] Child :net_sup_dynamic of Supervisor :kernel_sup started
Pid: #PID<0.151.0>
Start Call: :erl_distribution.start_link(%{name: :"manager-<project>-12415@127.0.0.1", supervisor: :net_sup_dynamic, net_tickintensity: 4, net_ticktime: 60, name_domain: :longnames, clean_halt: false})
Restart: :permanent
Shutdown: 1000
Type: :supervisor
14:20:27.287 [error] GenServer :"<project>::node_process" terminating
** (stop) :eacces
    (erts 14.0.2) :erlang.open_port({:spawn_executable, "/home/<user>/.cache/nvim/lspconfig/lexical/priv/port_wrapper.sh"}, [env: [{~c"MIX_HOME", ~c"/home/<user>/.asdf/installs/elixir/1.15.5-otp-26/.mix"}, {~c"PWD", ~c"/home/<user>/projects/client/<project>-web/<project>"}, {~c"ROOTDIR", ~c"/home/<user>/.asdf/installs/erlang/26.0.2"}, {~c"EDITOR", ~c"nvim"}, ...], cd: "/home/<user>/projects/client/<project>-web/<project>", args: ["/home/<user>/.asdf/installs/elixir/1.15.5-otp-26/bin/elixir", "--name", "project-<project>-12415@127.0.0.1", "--cookie", "lexical", "--no-halt", "-e", "Node.connect(:\"manager-<project>-12415@127.0.0.1\")", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/priv", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_common.ez/lx_common/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_elixir_sense.ez/lx_elixir_sense/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_lexical_plugin.ez/lx_lexical_plugin/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_lexical_shared.ez/lx_lexical_shared/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_lexical_test.ez/lx_lexical_test/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_path_glob.ez/lx_path_glob/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_remote_control.ez/lx_remote_control/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_sourceror.ez/lx_sourceror/ebin"]])
    (lx_remote_control 0.3.0) lib/lexical/remote_control/project_node.ex:43: LXical.RemoteControl.ProjectNode.State.start/3
    (lx_remote_control 0.3.0) lib/lexical/remote_control/project_node.ex:157: LXical.RemoteControl.ProjectNode.handle_call/3
    (stdlib 5.0.2) gen_server.erl:1113: :gen_server.try_handle_call/4
    (stdlib 5.0.2) gen_server.erl:1142: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message (from :"<project>::node"): {:start, [~c"/home/<user>/.cache/nvim/lspconfig/lexical/priv", ~c"/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_common.ez/lx_common/ebin", ~c"/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_elixir_sense.ez/lx_elixir_sense/ebin", ~c"/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_lexical_plugin.ez/lx_lexical_plugin/ebin", ~c"/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_lexical_shared.ez/lx_lexical_shared/ebin", ~c"/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_lexical_test.ez/lx_lexical_test/ebin", ~c"/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_path_glob.ez/lx_path_glob/ebin", ~c"/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_remote_control.ez/lx_remote_control/ebin", ~c"/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_sourceror.ez/lx_sourceror/ebin"]}
State: %{port: nil, status: :initializing, __struct__: LXical.RemoteControl.ProjectNode.State, project: %{__struct__: LXical.Project, project_module: nil, project_config: [], entropy: 12415, mix_exs_uri: "file:///home/<user>/projects/client/<project>-web/<project>/mix.exs", mix_project?: true, root_uri: "file:///home/<user>/projects/client/<project>-web/<project>", env_variables: %{}, mix_env: nil, mix_target: nil}, stopped_by: nil, started_by: nil, cookie: :lexical, stop_timeout: nil}
Client :"<project>::node" is alive

    (stdlib 5.0.2) gen.erl:259: :gen.do_call/4
    (elixir 1.15.5) lib/gen_server.ex:1071: GenServer.call/3
    (lx_remote_control 0.3.0) lib/lexical/remote_control/project_node.ex:108: LXical.RemoteControl.ProjectNode.start/2
    (lx_remote_control 0.3.0) lib/lexical/remote_control.ex:22: LXical.RemoteControl.start_link/1
    (lx_server 0.3.0) lib/lexical/server/project/node.ex:94: LXical.Server.Project.Node.start_node/1
    (lx_server 0.3.0) lib/lexical/server/project/progress/support.ex:17: LXical.Server.Project.Progress.Support.with_progress/3
    (lx_server 0.3.0) lib/lexical/server/project/node.ex:52: LXical.Server.Project.Node.init/1
    (stdlib 5.0.2) gen_server.erl:962: :gen_server.init_it/2
14:20:27.302 [error] Process :"<project>::node_process" (#PID<0.157.0>) terminating
** (ErlangError) Erlang error: :eacces:

  * 1st argument: invalid port name

    (erts 14.0.2) :erlang.open_port({:spawn_executable, "/home/<user>/.cache/nvim/lspconfig/lexical/priv/port_wrapper.sh"}, [env: [{~c"MIX_HOME", ~c"/home/<user>/.asdf/installs/elixir/1.15.5-otp-26/.mix"}, {~c"PWD", ~c"/home/<user>/projects/client/<project>-web/<project>"}, {~c"ROOTDIR", ~c"/home/<user>/.asdf/installs/erlang/26.0.2"}, {~c"EDITOR", ~c"nvim"}, ...], cd: "/home/<user>/projects/client/<project>-web/<project>", args: ["/home/<user>/.asdf/installs/elixir/1.15.5-otp-26/bin/elixir", "--name", "project-<project>-12415@127.0.0.1", "--cookie", "lexical", "--no-halt", "-e", "Node.connect(:\"manager-<project>-12415@127.0.0.1\")", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/priv", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_common.ez/lx_common/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_elixir_sense.ez/lx_elixir_sense/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_lexical_plugin.ez/lx_lexical_plugin/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_lexical_shared.ez/lx_lexical_shared/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_lexical_test.ez/lx_lexical_test/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_path_glob.ez/lx_path_glob/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_remote_control.ez/lx_remote_control/ebin", "-pa", "/home/<user>/.cache/nvim/lspconfig/lexical/lib/lx_sourceror.ez/lx_sourceror/ebin"]])
    (lx_remote_control 0.3.0) lib/lexical/remote_control/project_node.ex:43: LXical.RemoteControl.ProjectNode.State.start/3
    (lx_remote_control 0.3.0) lib/lexical/remote_control/project_node.ex:157: LXical.RemoteControl.ProjectNode.handle_call/3
    (stdlib 5.0.2) gen_server.erl:1113: :gen_server.try_handle_call/4
    (stdlib 5.0.2) gen_server.erl:1142: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

Reminds me of this patch to NextLS: https://github.com/elixir-tools/next-ls/compare/main...klalafudaklalafu:next-ls:node-hostname-fix

There was more context around it but I can't find the original issue/PR that I read for it (it was a few weeks ago and may have been on a different project), only https://github.com/elixir-tools/next-ls/issues/271#issuecomment-1751545073. It was some confluence of elixir versions and linux distributions.

**Comment by scohen** [comment]
So, @rktjmp, a couple of questions:
1. Is epmd running?
2. Is this a new problem, or was it occurring in 0.3.3?

(we already name our nodes `<project>-<entropy>@127.0.0.1`, so I don't think the fix above is relevant to us.

**Comment by rktjmp** [comment]
Yes, epmd output is included in the first post. 

I did not use 0.3.3.

**Comment by rktjmp** [comment]
I see the same error with 0.3.3 GH release.

**Comment by scohen** [comment]
Ok, it's good that this isn't a new issue :)

What I was asking is if epmd was running before the app started. 
I think what's going on is that your server node isn't starting distribution correctly. I don't understand why, we haven't had this bug reported before. Would you be amenable to a live debugging session on our discord?

**Comment by scohen** [comment]
@rktjmp Is this still happening for you?

**Comment by rktjmp** [comment]
Re discord, discussed that git-clone works when built with elixir 1.15.5-otp-26, erlang 26.0.2, decided to try building with elixir 1.13.4-otp-24 erlang 24.3.4.12 (same versions as gh release package is built with).

Have been unable to build that because erlang fails to compile `odbcserver.c`, unable to find symbols, etc. tried 24.3.4.13 with the same issues. I do have unixodbc installed which seems to be the recommended fix.

Have not had any time to really bug hunt _that_ issue yet...

**Comment by rktjmp** [comment]
Building `0bda057` with `.tool-versions`:

```
elixir          1.13.4-otp-24
erlang          24.3.4.13
```

and Lexical functions correctly, so its something specific to the GH release.

**Comment by rktjmp** [comment]
Using the 0.4.1 release, I do not see the previous port error, but also dont get any LSP behaviour though it is connected and running. There is nothing in neovims LSP log besides the .tool-versions file detection.

`[ERROR][2023-11-17 23:45:37] .../vim/lsp/rpc.lua:734	"rpc"	"/home/soup/.cache/nvim/lspconfig/lexical/bin/start_lexical.sh"	"stderr"	"Detected Elixir through asdf: /home/soup/.asdf/installs/elixir/1.15.5-otp-26/bin/elixir\n"`

**Comment by Tobi4161** [comment]
I tried making `priv/port_wrapper.sh` executable (`chmod +x priv/port_wrapper.sh`) and that seems to have worked for me

**Comment by rktjmp** [comment]
I can also confirm that after manually setting `priv/port_wrapper.sh` as executable, Lexical 0.4.1 downloaded from the GH release page works and as above, I dont see the original "invalid port name" with the 0.4.1 release.

**Comment by scohen** [comment]
@rktjmp can you test again with 0.5? there was a bug with packaging that caused the scripts not to be executable.

**Comment by rktjmp** [comment]
Confirming the Github 0.5 zip release works out of the box.

**Comment by scohen** [comment]
Sweet! Thanks for your patience.
