### ISSUE TITLE
lx_server exiting unexpected

### ISSUE THREAD

**Issue by Terbium-135** [lexical-lsp/lexical#454]
Lexical: **compiled from main**

> (though in the error log it's  `(lx_server 0.3.0)` ?

Project: **using elixir via rtx:**
```
elixir 1.15.7-otp-26 ~/projects/ganymed/.tool-versions 1.15.7-otp-26
erlang 26.1.2        ~/projects/ganymed/.tool-versions 26.1.2
```

Editor: **VS Code**

During editing I noticed an error message which did not get removed as well as no formatting happens anymore.
Until I realized lexical has crashed:
```

06:50:12.201 [error] Child LXical.Server of Supervisor LXical.Server.Supervisor terminated
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in LXical.Server.Provider.Queue.add/2
        (lx_server 0.3.0) lib/lexical/server/provider/queue.ex:154: LXical.Server.Provider.Queue.add(%LXical.Protocol.Requests.CodeAction{lsp: %LXical.Protocol.Requests.CodeAction.LSP{id: 2106, jsonrpc: "2.0", method: "textDocument/codeAction", context: #Protocol.Types.CodeAction.Context<[diagnostics: [#Protocol.Types.Diagnostic<[message: "** (Phoenix.LiveView.Tokenizer.ParseError) lib/backend_web/live/components/navbar.ex:51:9: attribute \"phx-hook\" requires the \"id\" attribute to be set\n   |\n48 |                     icon2_class={item.icon2_class}\n49 |                     path={item.path}\n50 |                     selected={item.selected}\n51 |                   >\n   |         ^\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/tag_engine.ex:1435: Phoenix.LiveView.TagEngine.raise_syntax_error!/3\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/tag_engine.ex:713: Phoenix.LiveView.TagEngine.handle_token/2\n    (elixir 1.15.7) lib/enum.ex:2510: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/tag_engine.ex:228: Phoenix.LiveView.TagEngine.handle_end/1\n    (eex 1.15.7) lib/eex/compiler.ex:432: EEx.Compiler.wrap_expr/5\n    (eex 1.15.7) lib/eex/compiler.ex:394: EEx.Compiler.generate_buffer/4\n    (eex 1.15.7) lib/eex/compiler.ex:355: EEx.Compiler.generate_buffer/4\n    (phoenix_live_view 0.20.1) expanding macro: Phoenix.Component.sigil_H/2\n", range: #Protocol.Types.Range<[start: #Protocol.Types.Position<[line: 50, character: 8]>, end: #Protocol.Types.Position<[line: 51, character: 0]>]>, source: "Elixir", severity: :error]>], trigger_kind: :automatic]>, partial_result_token: nil, range: #Protocol.Types.Range<[start: #Protocol.Types.Position<[line: 50, character: 31]>, end: #Protocol.Types.Position<[line: 50, character: 31]>]>, text_document: #Protocol.Types.TextDocument.Identifier<[uri: "file:///home/elixir-dev/projects/ganymed/lib/backend_web/live/components/navbar.ex"]>, work_done_token: nil}, document: nil, range: nil, id: 2106, jsonrpc: "2.0", method: "textDocument/codeAction", context: nil, partial_result_token: nil, text_document: nil, work_done_token: nil}, nil)
        (lx_server 0.3.0) lib/lexical/server.ex:123: LXical.Server.handle_message/2
        (lx_server 0.3.0) lib/lexical/server.ex:49: LXical.Server.handle_cast/2
        (stdlib 5.1.1) gen_server.erl:1103: :gen_server.try_handle_cast/3
        (stdlib 5.1.1) gen_server.erl:1165: :gen_server.handle_msg/6
        (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by scottming** [comment]
Hi, it looks like caused by a compiler error not be handled by eex, can you provider more detailed log from project.log? Or a minimal reproducing hex file.

**Comment by Terbium-135** [comment]
There is nothing recorded in the project.log:
```
2023-10-27T06:50:04.890927+02:00 info: Plugins found 0 results in 0.043 ms
2023-10-27T06:50:08.830581+02:00 info: Plugins found 0 results in 0.05 ms
2023-10-27T08:42:07.921126+02:00 info: Loaded [:lexical_credo]
```
Prior to the (FunctionClauseError) there is
```
Last message: {:"$gen_cast", {:protocol_message, %LXical.Protocol.Requests.CodeAction{lsp: %LXical.Protocol.Requests.CodeAction.LSP{id: 2105, jsonrpc: "2.0", method: "textDocument/codeAction", context: #Protocol.Types.CodeAction.Context<[diagnostics: [#Protocol.Types.Diagnostic<[message: "** (Phoenix.LiveView.Tokenizer.ParseError) lib/backend_web/live/components/navbar.ex:51:9: attribute \"phx-hook\" requires the \"id\" attribute to be set\n   |\n48 |                     icon2_class={item.icon2_class}\n49 |                     path={item.path}\n50 |                     selected={item.selected}\n51 |                   >\n   |         ^\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/tag_engine.ex:1435: Phoenix.LiveView.TagEngine.raise_syntax_error!/3\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/tag_engine.ex:713: Phoenix.LiveView.TagEngine.handle_token/2\n    (elixir 1.15.7) lib/enum.ex:2510: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/tag_engine.ex:228: Phoenix.LiveView.TagEngine.handle_end/1\n    (eex 1.15.7) lib/eex/compiler.ex:432: EEx.Compiler.wrap_expr/5\n    (eex 1.15.7) lib/eex/compiler.ex:394: EEx.Compiler.generate_buffer/4\n    (eex 1.15.7) lib/eex/compiler.ex:355: EEx.Compiler.generate_buffer/4\n    (phoenix_live_view 0.20.1) expanding macro: Phoenix.Component.sigil_H/2\n", range: #Protocol.Types.Range<[start: #Protocol.Types.Position<[line: 50, character: 8]>, end: #Protocol.Types.Position<[line: 51, character: 0]>]>, source: "Elixir", severity: :error]>], trigger_kind: :automatic]>, partial_result_token: nil, range: #Protocol.Types.Range<[start: #Protocol.Types.Position<[line: 50, character: 27]>, end: #Protocol.Types.Position<[line: 50, character: 27]>]>, text_document: #Protocol.Types.TextDocument.Identifier<[uri: "file:///home/elixir-dev/projects/ganymed/lib/backend_web/live/components/navbar.ex"]>, work_done_token: nil}, document: nil, range: nil, id: 2105, jsonrpc: "2.0", method: "textDocument/codeAction", context: nil, partial_result_token: nil, text_document: nil, work_done_token: nil}}}
State: %LXical.Server.State{configuration: nil, initialized?: false, shutdown_received?: false}
```

Only thing I remember (and visible in the error message as well):

- Added a phx-hook to an element
- Got a message to add an ID as well
- Added the ID
- And the `attribute phx-hook requires the ID attribute to be set` message persisted on screen because lexical was already gone

Perhaps I might able to reproduce it. Let's see...

**Comment by scottming** [comment]
I can't reproduce it with current information.

<img width="722" alt="CleanShot 2023-10-27 at 20 42 11@2x" src="https://github.com/lexical-lsp/lexical/assets/12830256/06c02dac-3240-4282-89e2-81bf6fbaded7">

When line 26 is deleted, diagnostics disappears.

**Comment by Terbium-135** [comment]
Can't reproduce either using VS Code.
Closing with being just a glitch.
