### ISSUE TITLE
`asdf` without elixir clashes with `rtx` elixir

### ISSUE THREAD

**Issue by GenericJam** [lexical-lsp/lexical#494]
If `asdf` is installed but isn't responsible for Elixir, `lexical` 'finds' asdf and tries to run with it but then everything crashes.

If `asdf` is completely absent it will run without issue.

```
Starting lexical release in "/Users/xxxx/code/lexical/_build/dev/package/lexical/bin"
[Trace - 5:34:13 PM] Sending request 'initialize - (0)'.
Detected Elixir through rtx: /Users/kevedey/.local/share/rtx/installs/elixir/1.14.0-otp-25/bin/elixir
[Trace - 5:34:37 PM] Received response 'initialize - (0)' in 24605ms.
[Trace - 5:34:37 PM] Sending notification 'initialized'.
[Trace - 5:34:37 PM] Sending notification 'textDocument/didOpen'.
[Trace - 5:34:37 PM] Received request 'client/registerCapability - (1)'.
[Trace - 5:34:37 PM] Sending response 'client/registerCapability - (1)'. Processing request took 1ms
[Trace - 5:34:37 PM] Received request 'window/workDoneProgress/create - (2)'.
[Trace - 5:34:37 PM] Sending response 'window/workDoneProgress/create - (2)'. Processing request took 0ms
[Trace - 5:34:37 PM] Received notification '$/progress'.
unknown command: elixir. Perhaps you have to reshim?
[Trace - 5:34:41 PM] Received notification '$/progress'.
[Trace - 5:37:00 PM] Sending request 'textDocument/hover - (1)'.
[Trace - 5:37:00 PM] Sending notification '$/cancelRequest'.
[Trace - 5:37:00 PM] Received response 1 without active response promise.
[Trace - 5:37:00 PM] Sending request 'textDocument/hover - (2)'.
[Trace - 5:37:00 PM] Received response 'textDocument/hover - (2)' in 12ms. Request failed: ** (ErlangError) Erlang error: {:erpc, :noconnection}
(kernel 8.4.2) erpc.erl:710: :[erpc.call/5](https://erpc.call/5)
(lx_server 0.3.0) lib/lexical/server/provider/handlers/hover.ex:30: LXical.Server.Provider.Handlers.Hover.hover_content/2
(lx_server 0.3.0) lib/lexical/server/provider/handlers/hover.ex:17: LXical.Server.Provider.Handlers.Hover.handle/2
(lx_server 0.3.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXical.Server.Provider.Queue.State.as_task/2
(elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
(elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
(stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
(-32603).
```
Having investigated the code a bit I believe the error is in this patch of code: https://github.com/lexical-lsp/lexical/blob/c2113daaf48d9ad92086a4973584497eec848788/apps/remote_control/lib/lexical/remote_control.ex#L82

**Comment by GenericJam** [comment]
This is probably being caused by my company VPN so probably false alarm.

It would be helpful to suppress this line from `asdf` to avoid false positives:
```
unknown command: elixir. Perhaps you have to reshim?
```

**Comment by scohen** [comment]
@GenericJam I'm closing this issue as we've learned it's due to your company's VPN settings and affects a bunch of things, lexical being one. 
Feel free to re-open if I'm mistaken.
