### ISSUE TITLE
Lexical Build crashes if the compiler exits

### ISSUE THREAD

**Issue by zimakki** [lexical-lsp/lexical#504]
steps: 

1. create a file in a project with the below content:
```elixir
defmodule Module do
  @after_verify {__MODULE__, :verify}
  # what happens if I do this
  def verify(_) do
    raise "whoops"
  end
end
```
Note: the above should give you a compile error similar to the below:
```shell
Compiling 21 files (.ex)
warning: redefining module Module (current version loaded from /Users/zimakki/.asdf/installs/elixir/1.15.4-otp-26/bin/../lib/elixir/ebin/Elixir.Module.beam)
  lib/testing.ex:1: Module (module)

** (UndefinedFunctionError) function Module.get_attribute/2 is undefined or private
    (elixir 1.15.4) Module.get_attribute(Module, :__impl__)
    (mix 1.15.4) lib/mix/compilers/elixir.ex:1172: Mix.Compilers.Elixir.detect_kind/1
    (mix 1.15.4) lib/mix/compilers/elixir.ex:1014: Mix.Compilers.Elixir.compiler_loop/4
    (mix 1.15.4) lib/mix/compilers/elixir.ex:173: Mix.Compilers.Elixir.compile/7
    (mix 1.15.4) lib/mix/state.ex:15: Mix.State.lock/2
    (mix 1.15.4) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.4) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.15.4) lib/mix/tasks/compile.all.ex:104: Mix.Tasks.Compile.All.compile/4
```

2. Close your editor and open it again... 

Note: lexical will crash and become unresponsive

**Comment by scohen** [comment]
(that's the issue that Zach submitted after our discord discussion)
