### ISSUE TITLE
Crash when importing macros

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#539]
I was typing the following and got a crash:
```elixir
import Entry, only: :m|
```

the crash was 
```
    ** (EXIT) exited in: GenServer.call({:via, :global, {LXical.Document.Store, 1091}}, {:fetch, "file:///Users/steve/Projects/lexical/apps/remote_control/lib/lexical/remote_control/search/store/backends/ets/state.ex"}, 5000)
        ** (EXIT) an exception was raised:
            ** (CaseClauseError) no case clause matching: :m
                (lx_common 0.3.0) lib/lexical/ast/analysis/import.ex:26: anonymous fn/2 in LXical.Ast.Analysis.Import.expand_selector/1
                (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
                (lx_common 0.3.0) lib/lexical/ast/analysis/import.ex:22: LXical.Ast.Analysis.Import.expand_selector/1
                (lx_common 0.3.0) lib/lexical/ast/analysis/import.ex:17: LXical.Ast.Analysis.Import.new/3
                (lx_common 0.3.0) lib/lexical/ast/analysis.ex:217: LXical.Ast.Analysis.analyze_node/2
                (lx_common 0.3.0) lib/lexical/ast/analysis.ex:72: anonymous fn/2 in LXical.Ast.Analysis.traverse/2
                (elixir 1.14.5) lib/macro.ex:635: anonymous fn/4 in Macro.do_traverse_args/4
                (stdlib 4.3.1.2) lists.erl:1462: :lists.mapfoldl_1/3
```

It's a simple fix, we need to import `:all` if we don't match any of the patterns.

**Comment by scohen** [comment]
Fixed by #546
