### ISSUE TITLE
VSCode Lexical client: couldn't create connection to server

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [lexical-lsp/lexical#813]
When starting VSCode on a machine with the following OS:

OS Name	Microsoft Windows 11 Home
Version	10.0.22631 Build 22631

I get this error which I can't fix.

```
2024-08-09 15:54:00.280 [info] Release override path is undefined, starting auto-install.
2024-08-09 15:54:00.858 [info] Latest release is "v0.7.0"
2024-08-09 15:54:00.863 [info] Looking for an installation manifest at path c:\Users\username\AppData\Roaming\Code\User\globalStorage\lexical-lsp.lexical\lexical_install\installation_manifest.json
2024-08-09 15:54:00.863 [info] Fetched the following manifest {"installedVersion":"0.7.0"}
2024-08-09 15:54:00.863 [info] Latest release is already installed. Skipping auto-install.
2024-08-09 15:54:00.868 [info] Starting Lexical in directory c:\Users\username\Documents\Workdir\market_manager\apps
2024-08-09 15:54:00.868 [info] Starting lexical release in "c:\Users\username\AppData\Roaming\Code\User\globalStorage\lexical-lsp.lexical\lexical_install\lexical\bin\start_lexical.sh"
2024-08-09 15:54:00.916 [info] [Error - 3:54:00 PM] Lexical client: couldn't create connection to server.
2024-08-09 15:54:00.916 [info] Error: spawn UNKNOWN
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:799:9)
	at c:\Users\username\.vscode\extensions\lexical-lsp.lexical-0.0.18\out\main.js:49:19271
	at async gh.createConnection (c:\Users\username\.vscode\extensions\lexical-lsp.lexical-0.0.18\out\main.js:46:12504)
	at async gh.start (c:\Users\username\.vscode\extensions\lexical-lsp.lexical-0.0.18\out\main.js:46:2730)
	at async HF (c:\Users\username\.vscode\extensions\lexical-lsp.lexical-0.0.18\out\main.js:55:22484)
	at async MF (c:\Users\username\.vscode\extensions\lexical-lsp.lexical-0.0.18\out\main.js:55:21286)
	at async m.n (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)
	at async m (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)
	at async m.l (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5829)
```

**Comment by scohen** [comment]
Lexical doesn't support Windows natively, only WSL is supported, but if you want to help make it work in windows, we'd love the support!
