### ISSUE TITLE
Formatting crashes sometimes when there are errors

### ISSUE THREAD

**Issue by Sleepful** [lexical-lsp/lexical#98]
formatting crashes because of errors, and then the project gets all wonky

symptoms include constant `LSP timeout` after the crash.

this is what it looks like in logs (using random ex project):

`project.log`

```
2023-04-06T14:42:35.512837-06:00 error: Supervisor: {local,'Elixir.LXRelease.RemoteControl.Supervisor'}. Context: child_terminated. Reason: {shutdown,1}. Offender: id='Elixir.LXRelease.RemoteControl.Build',pid=<0.972.0>.
```

`lexical.log`

```
14:42:30.925 [error] Formatter failed %BadArityError{function: &Code.format_string!/2, args: ["defmodule M.Application do\n  # See https://hexdocs.pm/elixir/Application.html\n  # for more information on OTP Applications\n  @moduledoc false\n\n  use Application\n\n  @impl true\n  def start(_type, _args) do\n    children = [\n      # Start the Telemetry supervisor\n      MWeb.Telemetry,\n      # Start the PubSub system\n      {Phoenix.PubSub, name: M.PubSub},\n      # Start Finch\n      {Finch, name: M.Finch},\n      # Start the Endpoint (http/https)\n      MWeb.Endpoint,\n      # Start a worker by calling: M.Worker.start_link(arg)\n      M.Data\n    ]\n\n    # See https://hexdocs.pm/elixir/Supervisor.html\n    # for other strategies and supported options\n    opts = [strategy: :one_for_one, name: M.Supervisor]\n    Supervisor.start_link(children, opts)\n  end\n\n  # Tell Phoenix to update the endpoint configuration\n  # whenever the application is updated.\n  @impl true\n  def config_change(changed, _new, removed) do\n    MWeb.Endpoint.config_change(changed, removed)\n    :ok\n  end\nend\n"]}
```

happened to me with file save.

Then it starts to do this:

```
14:46:25.925 [error] Process #PID<0.2436.0> terminating
** (exit) {:exception, {:shutdown, 1}}
    (kernel 8.5.3) erpc.erl:700: :erpc.call/5
    (server 0.1.0) lib/lexical/server/provider/handlers/formatting.ex:12: LXRelease.Server.Provider.Handlers.Formatting.handle/2
    (server 0.1.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXRelease.Server.Provider.Queue.State.as_task/2
    (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by wingyplus** [comment]
I think bad arity error should be fixed by https://github.com/lexical-lsp/lexical/commit/d5347990f88f947ee7861aa0ee368d766f4f3f62
